name: Bili_Food
data_root: /root/autodl-tmp/MMAG

text_path: /root/autodl-tmp/MMAG/Bili_Food/Bili_Food.csv
image_path: /root/autodl-tmp/MMAG/Bili_Food/Bili_FoodImages_extracted/Bili_FoodImages
graph_path: /root/autodl-tmp/MMAG/Bili_Food/Bili_FoodGraph.pt
v_emb_path: /root/autodl-tmp/MMAG/Bili_Food/image_features/Bili_Food_image_Qwen_Qwen2_VL_7B_Instruct_768d.npy
t_emb_path: /root/autodl-tmp/MMAG/Bili_Food/text_features/Bili_Food_text_Qwen_Qwen2_VL_7B_Instruct_768d.npy
train_ratio: 0.6
val_ratio: 0.2
lp_val_ratio: 0.1
lp_test_ratio: 0.2
edge_split_path: None
num_neg: 1000