name: Bili_Movie
data_root: /root/autodl-tmp/MMAG

text_path: /root/autodl-tmp/MMAG/Bili_Movie/Bili_Movie.csv
image_path: /root/autodl-tmp/MMAG/Bili_Movie/Bili_MovieImages_extracted/Bili_MovieImages
graph_path: /root/autodl-tmp/MMAG/Bili_Movie/Bili_MovieGraph.pt
v_emb_path: /root/autodl-tmp/MMAG/Bili_Movie/image_features/Bili_Movie_image_Qwen_Qwen2_VL_7B_Instruct_768d.npy
t_emb_path: /root/autodl-tmp/MMAG/Bili_Movie/text_features/Bili_Movie_text_Qwen_Qwen2_VL_7B_Instruct_768d.npy
train_ratio: 0.6
val_ratio: 0.2
lp_val_ratio: 0.1
lp_test_ratio: 0.2
edge_split_path: None
num_neg: 1000