name: Bili_Music
data_root: /root/autodl-tmp/MMAG

text_path: /root/autodl-tmp/MMAG/Bili_Music/Bili_Music.csv
image_path: /root/autodl-tmp/MMAG/Bili_Music/Bili_MusicImages_extracted/Bili_MusicImages
graph_path: /root/autodl-tmp/MMAG/Bili_Music/Bili_MusicGraph.pt
v_emb_path: /root/autodl-tmp/MMAG/Bili_Music/image_features/Bili_Music_image_Qwen_Qwen2_VL_7B_Instruct_768d.npy
t_emb_path: /root/autodl-tmp/MMAG/Bili_Music/text_features/Bili_Music_text_Qwen_Qwen2_VL_7B_Instruct_768d.npy
train_ratio: 0.6
val_ratio: 0.2
lp_val_ratio: 0.1
lp_test_ratio: 0.2
edge_split_path: None
num_neg: 1000