name: ele-fashion
data_root: /root/autodl-tmp/MMAG

text_path: /root/autodl-tmp/MMAG/cloth/cloth.csv
image_path: /root/autodl-tmp/MMAG/cloth/clothImages_extracted/clothImages
graph_path: /root/autodl-tmp/MMAG/cloth/clothGraph.pt
v_emb_path: /root/autodl-tmp/MMAG/cloth/image_features/cloth_image_Qwen_Qwen2_VL_7B_Instruct_768d.npy
t_emb_path: /root/autodl-tmp/MMAG/cloth/text_features/cloth_text_Qwen_Qwen2_VL_7B_Instruct_768d.npy
train_ratio: 0.6
val_ratio: 0.2
lp_val_ratio: 0.1
lp_test_ratio: 0.2
edge_split_path: None
num_neg: 1000