name: DY
data_root: /root/autodl-tmp/MMAG

text_path: /root/autodl-tmp/MMAG/DY/DY.csv
image_path: /root/autodl-tmp/MMAG/DY/DYImages_extracted/DYImages
graph_path: /root/autodl-tmp/MMAG/DY/DYGraph.pt
v_emb_path: /root/autodl-tmp/MMAG/DY/image_features/DY_image_Qwen_Qwen2_VL_7B_Instruct_768d.npy
t_emb_path: /root/autodl-tmp/MMAG/DY/text_features/DY_text_Qwen_Qwen2_VL_7B_Instruct_768d.npy
train_ratio: 0.6
val_ratio: 0.2
lp_val_ratio: 0.1
lp_test_ratio: 0.2
edge_split_path: None
num_neg: 1000