name: KU
data_root: /root/autodl-tmp/MMAG

text_path: /root/autodl-tmp/MMAG/KU/KU.csv
image_path: /root/autodl-tmp/MMAG/KU/KUImages_extracted/KUImages
graph_path: /root/autodl-tmp/MMAG/KU/KUGraph.pt
v_emb_path: /root/autodl-tmp/MMAG/KU/image_features/KU_image_Qwen_Qwen2_VL_7B_Instruct_768d.npy
t_emb_path: /root/autodl-tmp/MMAG/KU/text_features/KU_text_Qwen_Qwen2_VL_7B_Instruct_768d.npy
train_ratio: 0.6
val_ratio: 0.2
lp_val_ratio: 0.1
lp_test_ratio: 0.2
edge_split_path: None
num_neg: 1000