name: MultiMET_twitter
data_root: /root/autodl-tmp/MMAG

text_path: /root/autodl-tmp/MMAG/MultiMET_twitter/MultiMET_twitter.csv
image_path: /root/autodl-tmp/MMAG/MultiMET_twitter/MultiMET_twitterImages_extracted/MultiMET_twitterImages
graph_path: /root/autodl-tmp/MMAG/MultiMET_twitter/MultiMET_twitterGraph.pt
v_emb_path: /root/autodl-tmp/MMAG/MultiMET_twitter/image_features/MultiMET_twitter_image_Qwen2_VL_7B_Instruct_768d.npy
t_emb_path: /root/autodl-tmp/MMAG/MultiMET_twitter/text_features/MultiMET_twitter_text_Qwen2_VL_7B_Instruct_768d.npy
train_ratio: 0.6
val_ratio: 0.2
lp_val_ratio: 0.2
lp_test_ratio: 0.2
edge_split_path: None
num_neg: 5000