name: QB
data_root: /root/autodl-tmp/MMAG

text_path: /root/autodl-tmp/MMAG/QB/QB.csv
image_path: /root/autodl-tmp/MMAG/QB/QBImages_extracted/QBImages
graph_path: /root/autodl-tmp/MMAG/QB/QBGraph.pt
v_emb_path: /root/autodl-tmp/MMAG/QB/image_features/QB_image_Qwen_Qwen2_VL_7B_Instruct_768d.npy
t_emb_path: /root/autodl-tmp/MMAG/QB/text_features/QB_text_Qwen_Qwen2_VL_7B_Instruct_768d.npy
train_ratio: 0.6
val_ratio: 0.2
lp_val_ratio: 0.1
lp_test_ratio: 0.2
edge_split_path: None
num_neg: 1000