name: RedditS
data_root: /root/autodl-tmp/MMAG

text_path: /root/autodl-tmp/MMAG/RedditS/RedditS.csv
image_path: /root/autodl-tmp/MMAG/RedditS/RedditSImages_extracted/RedditSImages
graph_path: /root/autodl-tmp/MMAG/RedditS/RedditSGraph.pt
v_emb_path: /root/autodl-tmp/MMAG/RedditS/image_features/RedditS_image_Qwen_Qwen2_VL_7B_Instruct_768d.npy
t_emb_path: /root/autodl-tmp/MMAG/RedditS/text_features/RedditS_text_Qwen_Qwen2_VL_7B_Instruct_768d.npy
train_ratio: 0.6
val_ratio: 0.2
lp_val_ratio: 0.1
lp_test_ratio: 0.2
edge_split_path: None
num_neg: 1000