name: sports
data_root: /root/autodl-tmp/MMAG

text_path: /root/autodl-tmp/MMAG/sports/sports.csv
image_path: /root/autodl-tmp/MMAG/sports/sportsImages_extracted/sportsImages
graph_path: /root/autodl-tmp/MMAG/sports/sportsGraph.pt
v_emb_path: /root/autodl-tmp/MMAG/sports/image_features/sports_image_Qwen_Qwen2_VL_7B_Instruct_768d.npy
t_emb_path: /root/autodl-tmp/MMAG/sports/text_features/sports_text_Qwen_Qwen2_VL_7B_Instruct_768d.npy
train_ratio: 0.6
val_ratio: 0.2
lp_val_ratio: 0.2
lp_test_ratio: 0.2
edge_split_path: None
num_neg: 1000