name: TN
data_root: /root/autodl-tmp/MMAG

text_path: /root/autodl-tmp/MMAG/TN/TN.csv
image_path: /root/autodl-tmp/MMAG/TN/TNImages_extracted/TNImages
graph_path: /root/autodl-tmp/MMAG/TN/TNGraph.pt
v_emb_path: /root/autodl-tmp/MMAG/TN/image_features/TN_image_Qwen_Qwen2_VL_7B_Instruct_768d.npy
t_emb_path: /root/autodl-tmp/MMAG/TN/text_features/TN_text_Qwen_Qwen2_VL_7B_Instruct_768d.npy
train_ratio: 0.6
val_ratio: 0.2
lp_val_ratio: 0.1
lp_test_ratio: 0.2
edge_split_path: None
num_neg: 1000