name: Toys
data_root: /root/autodl-tmp/MMAG

text_path: /root/autodl-tmp/MMAG/Toys/Toys.csv
image_path: /root/autodl-tmp/MMAG/Toys/ToysImages_extracted/ToysImages
graph_path: /root/autodl-tmp/MMAG/Toys/ToysGraph.pt
v_emb_path: /root/autodl-tmp/MMAG/Toys/image_features/Toys_image_Qwen_Qwen2_VL_7B_Instruct_768d.npy
t_emb_path: /root/autodl-tmp/MMAG/Toys/text_features/Toys_text_Llama3_2_1B_Instruct_768d.npy
train_ratio: 0.6
val_ratio: 0.2
lp_val_ratio: 0.2
lp_test_ratio: 0.2
edge_split_path: None
num_neg: 5000