name: lp
n_epochs: 50
lr: 0.001
fewshots: False
weight_decay: 1e-5
n_runs: 3
batch_size: 1024

predictor_hidden: 256
predictor_out: 1
predictor_layers: 3
predictor_dropout: 0.02
k_list: [1,3,10]
num_neighbors: [5,5]
self_loop: False
undirected: False
lambda_v: 0.5
lambda_t: 0.5